services:
  db:
    image: postgres:16
    container_name: fraud_db

    env_file:
      - .env

    ports:
      - "${POSTGRES_PORT}:5432"

    volumes:
      - fraud_pgdata:/var/lib/postgresql/data
      - ./src/sql/01_schema.sql:/docker-entrypoint-initdb.d/01_schema.sql:ro

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
        ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: fraud_app

    ports:
      - "8501:8501"

    env_file:
      - .env

    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: "5432"

    restart: unless-stopped

volumes:
  fraud_pgdata: